#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_USB_DWC3) += usb30dev.o usb30reset.o cil.o cil_intr.o pcd.o pcd_intr.o
