#=======================================================================================
#	FileName    : Makefile
#	Description : FWDN(FirmWare DownLoader) Makefile
#=======================================================================================
#
#	TCC Board Support Package
#	Copyright (c) Telechips, Inc.
#	ALL RIGHTS RESERVED
#
#=======================================================================================

obj-$(CONFIG_TCC_SDMMC) += emmc.o
obj-$(CONFIG_TCC_SDMMC) += sd_bus.o
obj-$(CONFIG_TCC_SDMMC) += sd_hw.o
obj-$(CONFIG_TCC_SDMMC) += sd_memory.o
obj-$(CONFIG_TCC_SDMMC) += sd_slot.o
obj-$(CONFIG_TCC_SDMMC) += sd_update.o
obj-$(CONFIG_TCC_SDMMC) += partition_parser.o

#=======  end of file ==================================================================
