#=======================================================================================
#	FileName    : Makefile
#	Description : FWDN(FirmWare DownLoader) Makefile
#=======================================================================================
#
#	TCC Board Support Package
#	Copyright (c) Telechips, Inc.
#	ALL RIGHTS RESERVED
#
#=======================================================================================

#obj-$(CONFIG_FWDN_V7) += fwdn_main.o fwdn_protocol_v7.o fwdn_drv_v7.o
obj-y += fwdn_main.o fwdn_protocol_v7.o fwdn_drv_v7.o
#obj-$(CONFIG_FWDN_V7) += fwdn_nand.o
obj-y += fwdn_sdmmc.o
#obj-$(CONFIG_FWDN_V7) += fwupgrade.o
obj-y += fwupgrade.o

#=======  end of file ==================================================================
